/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bartersystem;

import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;

/**
 *
 * @author Sumeet
 */
public class ImageDisplayPanel extends javax.swing.JPanel {

    /**
     * Creates new form ImageDisplayPanel
     */
    ImageIcon icon;
    public ImageDisplayPanel(BufferedImage image) {
        
        icon = new ImageIcon(image);
        Image scaleImage = icon.getImage().getScaledInstance(160, 180, Image.SCALE_DEFAULT);
        icon.setImage(scaleImage);
        initComponents();
        jImage.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jImage = new javax.swing.JLabel();

        jImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bartersystem/images/blank.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jImage)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jImage)
        );

        jImage.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jImage;
    // End of variables declaration//GEN-END:variables
    protected ImageIcon createImageIcon(String path,
                                           String description) {
    java.net.URL imgURL = getClass().getResource(path);
    if (imgURL != null) {
        return new ImageIcon(imgURL, description);
    } else {
        System.err.println("Couldn't find file: " + path);
        return null;
    }
}

    private void getImage() {
        
    }


}
