/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bartersystem;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.ArrayList;
import javax.swing.JComponent;
import javax.swing.JOptionPane;

/**
 *
 * @author Sumeet
 */
public class LoginRegisterPanel extends javax.swing.JPanel implements KeyListener{

    String name,email,password;
    UserDatabaseAccess userEnterAccess;
    ProgramFrame programFrame;
    /**
     * Creates new form LoginProgramFrame
     */
    public LoginRegisterPanel(ProgramFrame programFrame) {
        this.programFrame = programFrame;
		// creating UserDatabaseAccess object
	userEnterAccess = new UserDatabaseAccess();
        initComponents();
    }

    /**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jNameText = new javax.swing.JLabel();
        jNameField = new javax.swing.JTextField();
        jEmailText = new javax.swing.JLabel();
        jEmailField = new javax.swing.JTextField();
        jPasswordText = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        RegisterButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jEmailText1 = new javax.swing.JLabel();
        jEmailLogin = new javax.swing.JTextField();
        jPasswordText1 = new javax.swing.JLabel();
        jPasswordLogin = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();

        jNameText.setText("Name");

        jEmailText.setText("Email");

        jPasswordText.setText("Password");

        RegisterButton.setText("Register");
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 195, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPasswordText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jNameText)
                        .addGap(113, 113, 113)
                        .addComponent(jNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jEmailText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(180, 180, 180))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(RegisterButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNameText)
                    .addComponent(jNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmailText)
                    .addComponent(jEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordText)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(RegisterButton)
                .addContainerGap(230, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sign Up", jPanel1);

        jEmailText1.setText("Username / Email ID");

        jEmailLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmailLoginActionPerformed(evt);
            }
        });

        jPasswordText1.setText("Password");

        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(149, 188, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jEmailText1)
                    .addComponent(jPasswordText1))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jEmailLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(178, 178, 178))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(LoginButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmailText1)
                    .addComponent(jEmailLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordText1)
                    .addComponent(jPasswordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(LoginButton)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Login", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        // TODO add your handling code here:
        savePerson();
        clear();
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void jEmailLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmailLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmailLoginActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        loginAuthenticate();
    }//GEN-LAST:event_LoginButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JTextField jEmailField;
    private javax.swing.JTextField jEmailLogin;
    private javax.swing.JLabel jEmailText;
    private javax.swing.JLabel jEmailText1;
    private javax.swing.JTextField jNameField;
    private javax.swing.JLabel jNameText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JPasswordField jPasswordLogin;
    private javax.swing.JLabel jPasswordText;
    private javax.swing.JLabel jPasswordText1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    private void loginAuthenticate() {
        
		email = jEmailLogin.getText();
                password = jPasswordLogin.getText();
                
                if (email.equals("")||password.equals("")) {
			JOptionPane.showMessageDialog(null,
					"Please enter complete details.");
		} else {
                    
                    
			//create a UserInfo object and pass it to UserDatabaseAccess to check it
			UserInfo person = new UserInfo(name, email, password);
                        boolean logged = userEnterAccess.check(person);
                        
                        if(logged){
                            
                            programFrame.getContentPane().removeAll();
                            person.setName(userEnterAccess.getPersonName(email,password));
                            person.setId(userEnterAccess.getPersonId(email,password));
                            UserLoggedInPanel usp = new UserLoggedInPanel(programFrame,person);
                            programFrame.setContentPane(usp);
                            ((JComponent) programFrame.getContentPane()).revalidate();
                            programFrame.repaint();
                        }
                        
                        
			
		}
                
        
    }
    
    public void savePerson() {
		name = jNameField.getText();
		name = name.toUpperCase(); //Save all names in Uppercase
		
		email = jEmailField.getText();
                password = jPasswordField.getText();
		if (name.equals("")||password.equals("")||name.equals("")) {
			JOptionPane.showMessageDialog(null,
					"Please enter complete details.");
		} else {
                    
                    
			//create a UserInfo object and pass it to UserDatabaseAccess to save it
			UserInfo person = new UserInfo(name, email, password);
                        boolean validation = userEnterAccess.savePerson(person);
                        if(validation){
                            
                            JOptionPane.showMessageDialog(null, "Person registered & logged in");
                        
                            programFrame.getContentPane().removeAll();
                            person.setId(userEnterAccess.getPersonId(email,password));
                            UserLoggedInPanel usp = new UserLoggedInPanel(programFrame,person);
                            programFrame.setContentPane(usp);
                            ((JComponent) programFrame.getContentPane()).revalidate();
                            programFrame.repaint();
                        }
                        else{
                            clear();
                        }
                        
		}
	}
    
    
    
    public void clear() {
		jNameField.setText("");
		jEmailField.setText("");
                jPasswordField.setText("");
	}

    @Override
    public void keyTyped(KeyEvent ke) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void keyPressed(KeyEvent ke) {
        if (ke.getKeyCode()==KeyEvent.VK_ENTER){
            if(jTabbedPane1.getSelectedIndex()==1){
                savePerson();
                clear();
            }
            else if(jTabbedPane1.getSelectedIndex()==2){
                loginAuthenticate();
            }
        }
    }

    @Override
    public void keyReleased(KeyEvent ke) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    

}
