/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bartersystem;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Sumeet
 */
public class ProductDetailPanel extends javax.swing.JPanel {

    
    ProgramFrame programFrame;
    int productIndex,userIndex;
    UserDatabaseAccess userAccess;
    /**
     * Creates new form ProductDetailPanel
     * @param programFrame
     * @param productIndex
     * @param user
     */
    public ProductDetailPanel(ProgramFrame programFrame, int productIndex,int userIndex) {
        
        this.programFrame = programFrame;
        this.productIndex = productIndex;
        this.userIndex = userIndex;
        userAccess = new UserDatabaseAccess();
        initComponents();
        setComponents();
    }

    /**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProductName = new javax.swing.JLabel();
        jProductCategory = new javax.swing.JLabel();
        jTraderName = new javax.swing.JLabel();
        jTraderEmail = new javax.swing.JLabel();
        jQuantity = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jExpectationText = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jProductDescription = new javax.swing.JLabel();
        jDeleteButton = new javax.swing.JButton();
        jViewImage = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(400, 300));

        jProductName.setText("Product Name");

        jProductCategory.setText("Category : ");

        jTraderName.setText("Trader:");

        jTraderEmail.setText("Trader email-id : ");

        jQuantity.setText("Quantity Available :");

        jLabel7.setText("Trader Expects :");

        jExpectationText.setText("expectation text");
        jExpectationText.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel6.setText("Description :");

        jProductDescription.setText("description text");
        jProductDescription.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jDeleteButton.setText("Delete Item");
        jDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteButtonActionPerformed(evt);
            }
        });

        jViewImage.setText("View Image");
        jViewImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jViewImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jExpectationText, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jProductName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jViewImage)
                                .addGap(14, 14, 14))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jQuantity)
                                    .addComponent(jTraderEmail)
                                    .addComponent(jProductCategory)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jProductDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTraderName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDeleteButton)
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jProductName)
                    .addComponent(jViewImage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProductCategory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jProductDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTraderName)
                    .addComponent(jDeleteButton))
                .addGap(13, 13, 13)
                .addComponent(jTraderEmail)
                .addGap(14, 14, 14)
                .addComponent(jQuantity)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jExpectationText, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteButtonActionPerformed
        // TODO add your handling code here:
        deleteItem();
    }//GEN-LAST:event_jDeleteButtonActionPerformed

    private void jViewImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jViewImageActionPerformed
        try {
            // TODO add your handling code here:
            displayImage();
        } catch (IOException ex) {
            Logger.getLogger(ProductDetailPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jViewImageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jDeleteButton;
    private javax.swing.JLabel jExpectationText;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jProductCategory;
    private javax.swing.JLabel jProductDescription;
    private javax.swing.JLabel jProductName;
    private javax.swing.JLabel jQuantity;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jTraderEmail;
    private javax.swing.JLabel jTraderName;
    private javax.swing.JButton jViewImage;
    // End of variables declaration//GEN-END:variables

    private void setComponents() {
        jProductName.setText(userAccess.getProductName(productIndex));
        jProductCategory.setText("Category : "+userAccess.getProductCategory(productIndex));
        jProductDescription.setText(userAccess.getProductDescription(productIndex));
        jExpectationText.setText(userAccess.getProductExpectation(productIndex));
        jTraderName.setText("Trader: "+userAccess.getUserName(userIndex));
        jTraderEmail.setText("Trader email-id : "+userAccess.getUserEmail(userIndex));
        jQuantity.setText("Quantity available : "+userAccess.getQuantity(productIndex));
    }

    private void deleteItem() {
        userAccess.deleteProduct(productIndex);
        JOptionPane.showMessageDialog(null,"Product Deleted");
    }

    private void displayImage() throws IOException {
        BufferedImage bImage = userAccess.getProductImage(productIndex);
        JOptionPane.showMessageDialog(null,new ImageDisplayPanel(bImage),"Product Image",JOptionPane.PLAIN_MESSAGE);
    }
}
