/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bartersystem;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Sumeet
 */
public class ProductConfirmTrade extends javax.swing.JPanel {

    
    ProgramFrame programFrame;
    int UserProductIndex,TraderProductIndex,userIndex,traderIndex;
    UserDatabaseAccess userAccess;
    /**
     * Creates new form ProductDetailPanel
     * @param programFrame
     * @param UserProductIndex
     * @param userIndex
     * @param TraderProductIndex
     * @param traderIndex
     */
    public ProductConfirmTrade(ProgramFrame programFrame, int UserProductIndex,int TraderProductIndex,int userIndex, int traderIndex) {
        
        this.programFrame = programFrame;
        
        this.UserProductIndex = UserProductIndex;
        this.TraderProductIndex = TraderProductIndex;
        
        this.userIndex = userIndex;
        this.traderIndex = traderIndex;
        
        userAccess = new UserDatabaseAccess();
        
        initComponents();
        setComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProductName = new javax.swing.JLabel();
        jProductCategory = new javax.swing.JLabel();
        jTraderName = new javax.swing.JLabel();
        jTraderEmail = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jProductDescription = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jOfferedProductDescription = new javax.swing.JLabel();
        jAccept = new javax.swing.JButton();
        jReject = new javax.swing.JButton();
        jTraderProductName = new javax.swing.JLabel();
        jTraderProductCategory = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(400, 300));

        jProductName.setText("Product Name");

        jProductCategory.setText("Category : ");

        jTraderName.setText("Trader:");

        jTraderEmail.setText("Trader email-id : ");

        jLabel6.setText("Description :");

        jProductDescription.setText("description text");
        jProductDescription.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel1.setText("Product Description :");

        jOfferedProductDescription.setText("description text");
        jOfferedProductDescription.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jAccept.setText("Accept Trade");
        jAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAcceptActionPerformed(evt);
            }
        });

        jReject.setText("Reject Trade");
        jReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRejectActionPerformed(evt);
            }
        });

        jTraderProductName.setText("Product Name :");

        jTraderProductCategory.setText("Product Category :");

        jButton1.setText("View Image");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(10, 10, 10)
                                .addComponent(jProductDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTraderEmail)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jOfferedProductDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProductName)
                            .addComponent(jProductCategory))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jAccept)
                            .addComponent(jReject))
                        .addGap(67, 67, 67))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTraderProductName)
                            .addComponent(jTraderProductCategory))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTraderName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(79, 79, 79))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jProductName)
                    .addComponent(jAccept))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jProductCategory)
                    .addComponent(jReject))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jProductDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jTraderName))
                .addGap(10, 10, 10)
                .addComponent(jTraderEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTraderProductName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTraderProductCategory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jOfferedProductDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAcceptActionPerformed
        // TODO add your handling code here:
        addTradeStatus(true);
    }//GEN-LAST:event_jAcceptActionPerformed

    private void jRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRejectActionPerformed
        // TODO add your handling code here:
        addTradeStatus(false);
    }//GEN-LAST:event_jRejectActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            displayImage();
        } catch (IOException ex) {
            Logger.getLogger(ProductConfirmTrade.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAccept;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jOfferedProductDescription;
    private javax.swing.JLabel jProductCategory;
    private javax.swing.JLabel jProductDescription;
    private javax.swing.JLabel jProductName;
    private javax.swing.JButton jReject;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jTraderEmail;
    private javax.swing.JLabel jTraderName;
    private javax.swing.JLabel jTraderProductCategory;
    private javax.swing.JLabel jTraderProductName;
    // End of variables declaration//GEN-END:variables

    private void setComponents() {
        jProductName.setText(userAccess.getProductName(UserProductIndex));
        jProductCategory.setText("Category : "+userAccess.getProductCategory(UserProductIndex));
        jProductDescription.setText(userAccess.getProductDescription(UserProductIndex));
        jTraderName.setText("Trader: "+userAccess.getUserName(traderIndex));
        jTraderEmail.setText("Trader email-id : "+userAccess.getUserEmail(traderIndex));
        jTraderProductName.setText("Product Name: "+userAccess.getProductName(TraderProductIndex));
        jTraderProductCategory.setText("Product Category: "+userAccess.getProductCategory(TraderProductIndex));
        jOfferedProductDescription.setText(userAccess.getProductDescription(TraderProductIndex));
    }

    private void addTradeStatus(boolean status) {
        if(status){
            userAccess.addTradeStatus(userIndex,traderIndex,UserProductIndex,TraderProductIndex,"SUCCESSFUL");
            
        }
        else{
            userAccess.addTradeStatus(userIndex,traderIndex,UserProductIndex,TraderProductIndex,"FAILED");
        }    
        
    }

    private void displayImage() throws IOException {
        BufferedImage bImage = userAccess.getProductImage(TraderProductIndex);
        JOptionPane.showMessageDialog(null,new ImageDisplayPanel(bImage),"Product Image",JOptionPane.PLAIN_MESSAGE);
    }

    
    
}
