/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bartersystem;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Sumeet
 */
public class ProductExchangedPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductExchanged
     */
    int tradeIndex;
    ImageIcon icon;
    UserDatabaseAccess userAccess;
    BufferedImage image;
    Image scaleImage;
    
    public ProductExchangedPanel(int tradeIndex) {
        this.tradeIndex = tradeIndex;
        userAccess = new UserDatabaseAccess();
        initComponents();
        try {
            setComponents();
        } catch (IOException ex) {
            Logger.getLogger(ProductExchangedPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProductName1 = new javax.swing.JLabel();
        jProductOne = new javax.swing.JLabel();
        jProductName2 = new javax.swing.JLabel();
        jProductTwo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jTraderOne = new javax.swing.JLabel();
        jTraderTwo = new javax.swing.JLabel();
        jTradeID = new javax.swing.JLabel();
        jCategoryOne = new javax.swing.JLabel();
        jCategoryTwo = new javax.swing.JLabel();
        jStatus = new javax.swing.JLabel();

        jProductName1.setText("Product Name 1");

        jProductOne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bartersystem/images/blank.png"))); // NOI18N
        jProductOne.setText("jLabel2");

        jProductName2.setText("Product Name 2");

        jProductTwo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bartersystem/images/blank.png"))); // NOI18N
        jProductTwo.setText("jLabel4");

        jTraderOne.setText("jLabel1");

        jTraderTwo.setText("jLabel2");

        jTradeID.setText("jLabel3");

        jCategoryOne.setText("jLabel1");

        jCategoryTwo.setText("jLabel2");

        jStatus.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProductOne, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProductName1)
                    .addComponent(jTraderOne)
                    .addComponent(jTradeID)
                    .addComponent(jCategoryOne))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jProductTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(43, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCategoryTwo)
                                    .addComponent(jTraderTwo)
                                    .addComponent(jProductName2))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jStatus)
                        .addGap(107, 107, 107))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTradeID)
                    .addComponent(jStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTraderOne)
                    .addComponent(jTraderTwo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jProductName1)
                    .addComponent(jProductName2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCategoryOne)
                    .addComponent(jCategoryTwo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jProductOne)
                    .addComponent(jProductTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jCategoryOne;
    private javax.swing.JLabel jCategoryTwo;
    private javax.swing.JLabel jProductName1;
    private javax.swing.JLabel jProductName2;
    private javax.swing.JLabel jProductOne;
    private javax.swing.JLabel jProductTwo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jStatus;
    private javax.swing.JLabel jTradeID;
    private javax.swing.JLabel jTraderOne;
    private javax.swing.JLabel jTraderTwo;
    // End of variables declaration//GEN-END:variables

    private void setComponents() throws IOException {
        
        jTradeID.setText("Trade # "+tradeIndex);
        
        int productOne = userAccess.getProductOneFromTrade(tradeIndex);
        int productTwo = userAccess.getProductTwoFromTrade(tradeIndex);
        
        int traderOne = userAccess.getUserId(productOne);
        int traderTwo = userAccess.getUserId(productTwo);
        
        jTraderOne.setText(userAccess.getUserName(traderOne));
        jTraderTwo.setText(userAccess.getUserName(traderTwo));
        
        jProductName1.setText(userAccess.getProductName(productOne));
        jProductName2.setText(userAccess.getProductName(productTwo));
        
        jCategoryOne.setText("Type: "+userAccess.getProductCategory(productOne));
        jCategoryTwo.setText("Type: "+userAccess.getProductCategory(productTwo));
        
        jStatus.setText("Status: "+userAccess.getTradeStatus(tradeIndex));
        
        image = userAccess.getProductImage(productOne);
        icon = new ImageIcon(image);
        scaleImage = icon.getImage().getScaledInstance(160, 180, Image.SCALE_DEFAULT);
        icon.setImage(scaleImage);
        jProductOne.setIcon(icon);
        
        image = userAccess.getProductImage(productTwo);
        icon = new ImageIcon(image);
        scaleImage = icon.getImage().getScaledInstance(160, 180, Image.SCALE_DEFAULT);
        icon.setImage(scaleImage);
        jProductTwo.setIcon(icon);
    }
}
